import { useEffect, useState } from 'react'
import type { AuditIssue, Version } from './types'
import { ArtifactButtons, Badge, Button, EmptyState, ModeBadge, ScreenHeading, SlidePreview, qualityLabel, qualityTone } from './ui'
import { Icon } from './icons'

type Filter = 'all' | 'blocking' | 'warning'

export default function AuditPage({ version, issues, selectedIssueIds, busy, onToggleIssue, onRepair, onBack, onError }: { version: Version | null; issues: AuditIssue[]; selectedIssueIds: string[]; busy: string | null; onToggleIssue: (id: string) => void; onRepair: () => Promise<void>; onBack: () => void; onError: (message: string) => void }) {
  const [filter, setFilter] = useState<Filter>('all')
  const [slideIndex, setSlideIndex] = useState(0)
  useEffect(() => { setSlideIndex(0); setFilter('all') }, [version?.id])
  const blockingCount = issues.filter(issue => isBlocking(issue.severity)).length
  const warningCount = issues.length - blockingCount
  const visible = issues.filter(issue => filter === 'all' || (filter === 'blocking' ? isBlocking(issue.severity) : !isBlocking(issue.severity)))
  const automaticSelectedCount = selectedIssueIds.filter(id => issues.find(issue => issue.id === id)?.repairability !== 'manual').length
  const manualSelectedCount = selectedIssueIds.length - automaticSelectedCount
  return <div className="page">
    <ScreenHeading eyebrow="ПРОВЕРКА КАЧЕСТВА" title="Аудит презентации" description="Посмотрите замечания, выберите нужные исправления и получите новую проверенную версию." action={<Button variant="secondary" onClick={onBack} icon={<Icon name="arrow" size={16} style={{ transform: 'rotate(180deg)' }} />}>К вариантам</Button>} />
    {!version ? <EmptyState icon="shield" title="Сначала выберите вариант" description="Откройте один из вариантов презентации, чтобы увидеть его отчёт проверки." action={<Button onClick={onBack}>Перейти к вариантам</Button>} /> : <div className="audit-layout">
      <div className="audit-main">
        <section className="card audit-preview"><div className="audit-preview__header"><div><h2>Предпросмотр</h2><p>{version.preview_urls?.length ? `Слайд ${slideIndex + 1} из ${version.preview_urls.length}` : 'Предпросмотр пока недоступен'}</p></div><div className="audit-preview__badges"><ModeBadge version={version} /><Badge tone={qualityTone(version.quality_status)}>{qualityLabel(version.quality_status)}</Badge></div></div><SlidePreview url={version.preview_urls?.[slideIndex]} index={slideIndex} /><div className="audit-preview__controls"><Button variant="ghost" disabled={slideIndex === 0} onClick={() => setSlideIndex(i => i - 1)}>Назад</Button><span>{version.preview_urls?.length ? `${slideIndex + 1} / ${version.preview_urls.length}` : '—'}</span><Button variant="ghost" disabled={slideIndex >= (version.preview_urls?.length || 1) - 1} onClick={() => setSlideIndex(i => i + 1)}>Вперёд</Button></div></section>
        <section className="card audit-files"><div><h3>Файлы варианта</h3><p>Скачайте презентацию и отчёты после проверки.</p></div><ArtifactButtons version={version} onError={onError} /></section>
      </div>
      <section className="card issue-panel"><div className="issue-panel__header"><div><p className="eyebrow">ЗАМЕЧАНИЯ</p><h2>{issues.length ? `${issues.length} ${plural(issues.length, 'замечание', 'замечания', 'замечаний')}` : 'Замечаний нет'}</h2></div><div className="issue-counts"><span className="issue-counts__blocking">{blockingCount} важных</span><span>{warningCount} остальных</span></div></div>
        {issues.length ? <><div className="filter-tabs" role="tablist" aria-label="Фильтр замечаний"><button type="button" className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>Все</button><button type="button" className={filter === 'blocking' ? 'active' : ''} onClick={() => setFilter('blocking')}>Важные</button><button type="button" className={filter === 'warning' ? 'active' : ''} onClick={() => setFilter('warning')}>Остальные</button></div><div className="issue-list">{visible.length ? visible.map(issue => <label key={issue.id} className={`issue-item ${selectedIssueIds.includes(issue.id) ? 'issue-item--selected' : ''} ${issue.repairability === 'manual' ? 'issue-item--manual' : ''}`}><input type="checkbox" checked={selectedIssueIds.includes(issue.id)} onChange={() => onToggleIssue(issue.id)} /><span className="issue-item__check"><Icon name="check" size={13} /></span><span className="issue-item__body"><span className="issue-item__top"><strong>{issueTitle(issue.rule_id)}</strong><Badge tone={isBlocking(issue.severity) ? 'danger' : 'warning'}>{isBlocking(issue.severity) ? 'Важно' : 'Замечание'}</Badge></span><span className="issue-item__meta">{issue.slide_id ? `Слайд ${issue.slide_id.replace(/^slide_/, '')}` : 'Презентация целиком'}{issue.object_id ? ` · Объект ${issue.object_id}` : ''}{issue.repairability === 'manual' ? ' · Требует ручного исправления' : ''}</span><span className="issue-item__evidence">{evidenceText(issue.evidence)}</span>{issue.resolution && <span className="issue-item__resolution">Статус: {issue.resolution}</span>}</span></label>) : <p className="empty-filter">В этой категории замечаний нет.</p>}</div><div className="issue-panel__footer"><div><strong>Выбрано: {selectedIssueIds.length}</strong><span>{manualSelectedCount ? `${manualSelectedCount} требуют правки на слайде. ` : ''}Автоматические исправления создают новую версию.</span></div><Button onClick={() => automaticSelectedCount ? void onRepair() : onBack()} disabled={!selectedIssueIds.length || Boolean(busy)} icon={<Icon name={automaticSelectedCount ? 'spark' : 'arrow'} size={17} />}>{busy === 'repair' ? 'Запускаем…' : automaticSelectedCount ? `Исправить автоматически (${automaticSelectedCount})` : 'Открыть для правки'}</Button></div></> : <div className="issue-clean"><div className="issue-clean__icon"><Icon name="check" size={26} /></div><h3>Проверка не нашла замечаний</h3><p>Это результат текущего автоматического аудита. Вы можете просмотреть и скачать файлы варианта.</p></div>}
      </section>
    </div>}
  </div>
}

function isBlocking(severity: string) { return ['blocking', 'critical', 'error', 'high'].includes(severity.toLowerCase()) }
function evidenceText(evidence: AuditIssue['evidence']) {
  if (typeof evidence === 'string') return evidence
  const description = evidence.message || evidence.description || evidence.detail
  if (typeof description === 'string') return description
  return Object.entries(evidence).map(([key, value]) => `${key.replaceAll('_', ' ')}: ${String(value)}`).join(' · ')
}
function issueTitle(ruleId: string) {
  const titles: Record<string, string> = { text_overflow: 'Текст не помещается', possible_text_overflow: 'Возможно, текст не помещается', out_of_bounds: 'Объект за пределами слайда', overlap: 'Пересечение объектов', low_contrast: 'Недостаточный контраст', unsupported_fact: 'Факт без источника', missing_source: 'Нет источника данных', placeholder: 'Остался служебный текст', old_content: 'Остался текст шаблона', old_template_content: 'Остался текст шаблона', unverified_number: 'Число без подтверждённого источника', unknown_fact_id: 'Источник факта не найден', empty_slide: 'Пустой слайд', font_mismatch: 'Шрифт не из шаблона', color_mismatch: 'Цвет не из палитры', image_distortion: 'Искажено изображение', duplicate_slide: 'Повтор слайда', duplicate_content: 'Тезисы повторяют другой слайд', font_size_mismatch: 'Кегль не из шаблона', font_not_embedded: 'Шрифт не встроен в файл', font_substituted: 'Шрифт шаблона подменён при отрисовке', text_text_overlap: 'Текстовые рамки пересекаются', text_image_overlap: 'Текст на изображении', small_body_text: 'Мелкий текст', rendered_text_overflow: 'Текст выходит за рамку в PDF', rendered_text_overlap: 'Текст перекрывается в PDF', rendered_text_image_overlap: 'Текст на изображении в PDF', rendered_text_missing: 'Текст не найден в PDF', visual_audit_incomplete: 'Визуальная проверка не завершена', off_palette_color: 'Цвет не из палитры шаблона', misaligned_block: 'Блок не на направляющих макета', margin_intrusion: 'Блок заходит в поля', image_distorted: 'Изображение растянуто', brand_moved: 'Логотип или колонтитул сдвинут', slide_underfilled: 'Слайд заполнен меньше чем на четверть', slide_overfilled: 'Слайд заполнен больше чем на три четверти', chart_axis_unlabeled: 'У диаграммы нет подписей осей или единиц' }
  return titles[ruleId] || ruleId.replaceAll('_', ' ').replace(/^./, first => first.toUpperCase())
}
function plural(value: number, one: string, few: string, many: string) { const n = value % 100; const last = n % 10; return n > 10 && n < 20 ? many : last === 1 ? one : last >= 2 && last <= 4 ? few : many }
